### ISSUE TITLE
Can't use --config to define login file location

### ISSUE THREAD

**Issue by amounierlltech** [keeneyetech/ecli#42]
I use release 0.10 for windows 64. 
I try to login using --config flag, but always have error 1 in return.
I created a .ecli.json somewhere as defined in login standard output, but json format is not exact in this message. missing " after password, and additionnal coma after url. But fixing format didn't allow me to connect.
I type : ecli login platform --config "D:\myfolder\.ecli.json" 
What should be --config argument syntax, are windows paths accepted ? is it folder of file path ?

**Comment by matm** [comment]
Looks like your JSON config file is malformed maybe. It must look like
```
{"platform": {"login": "yourlogin", "password": "yourpassword", "url": "https://yoururl/api/v2"}}
```
Just create it in your local directory and call it by filename:
```
ecli login platform --config myfile.json
```

You can remove the dot `.` at the beginning on the file name and use any name like `myfile.json`.

**Comment by amounierlltech** [comment]
It's working with this syntax, thx for your support.
